trigger:
  branches:
    include:
      - main  # Trigger pipeline on push to main branch

variables:
  deploy_cr: myacrregistry9390                # Your Azure Container Registry name (without .azurecr.io)
  deploy_version: $(Build.BuildId)            # Unique version tag for each build

stages:
- stage: Build
  displayName: Build & Push Docker Image
  jobs:
    - job: BuildAndPush
      displayName: Build and Push Image
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: Docker@2
          displayName: Build and Push to ACR
          inputs:
            command: buildAndPush
            repository: node-app                         # Image name
            dockerfile: Dockerfile
            containerRegistry: my-acr-conn               # Docker Registry service connection
            tags: |
              $(deploy_version)

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
    - job: DeployToAKS
      displayName: Deploy Application to Kubernetes
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: FileTransform@2
          displayName: Replace image tag in manifest.yaml
          inputs:
            folderPath: '$(System.DefaultWorkingDirectory)'
            fileType: 'yaml'
            targetFiles: '**/manifest.yaml'

        - task: Kubernetes@1
          displayName: Apply Kubernetes Manifest
          inputs:
            connectionType: Azure Resource Manager
            azureSubscription: my-azure-conn             # Azure service connection name
            azureResourceGroup: my-rg                    # Your resource group
            kubernetesCluster: my-aks-cluster            # Your AKS cluster
            namespace: my-app
            command: apply
            useConfigurationFile: true
            configuration: |
              manifest.yaml
